Test exit if changes to format

diff --git a/.github/workflows/terraform-format-check.yml b/.github/workflows/terraform-format-check.yml
--- a/.github/workflows/terraform-format-check.yml
+++ b/.github/workflows/terraform-format-check.yml
@@ -20,3 +20,12 @@ jobs:
                 cd terraform
                 pwd
                 terraform fmt --recursive
+                if [[ $(terraform fmt --recursive) ]]; then
+                    echo "::group::"
+                    echo "::error::The code is not formatted correctly. Run the following locally and commit the changes before proceeding:"
+                    echo "terraform fmt --recursive"
+                    echo "::endgroup::"
+                    exit 1
+                else
+                    echo "Nothing to format, you can proceed."
+                fi
